### ISSUE TITLE
avro error

### ISSUE THREAD

**Issue by priyolahiri** [dnmilne/wikipediaminer#20]
after doing a maven compile and running the hadoop job this is what I get:

java.lang.Exception: java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:403)
Caused by: java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;
    at org.apache.avro.mapred.AvroSerialization.getSerializer(AvroSerialization.java:107)
    at org.apache.hadoop.io.serializer.SerializationFactory.getSerializer(SerializationFactory.java:82)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.init(MapTask.java:986)
    at org.apache.hadoop.mapred.MapTask.createSortingCollector(MapTask.java:390)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:418)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
14/03/19 00:41:40 INFO mapreduce.Job: Job job_local1813272804_0001 running in uber mode : false
14/03/19 00:41:40 INFO mapreduce.Job:  map 0% reduce 0%
14/03/19 00:41:40 INFO mapreduce.Job: Job job_local1813272804_0001 failed with state FAILED due to: NA
14/03/19 00:41:40 INFO mapreduce.Job: Counters: 0
Exception in thread "main" java.io.IOException: Job failed!
    at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:836)
    at org.wikipedia.miner.extract.steps.pageSummary.PageSummaryStep.run(PageSummaryStep.java:170)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.wikipedia.miner.extract.DumpExtractor.run(DumpExtractor.java:224)
    at org.wikipedia.miner.extract.DumpExtractor.main(DumpExtractor.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

I have hadoop 2.2.0

**Comment by babarbirra** [comment]
Hi,
I experience the same error.
Did you manage to solve it?
I use hadoop 2.5.2

**Comment by priyolahiri** [comment]
Nope
