### ISSUE TITLE
ant build-database fails

### ISSUE THREAD

**Issue by vshvedov** [dnmilne/wikipediaminer#28]
Tested using 6,7,8 JDK, Ubuntu 15.04 x64 - it keep fails with an output:

```
     [java] 15/08/07 20:45:37 INFO db.MarkupDatabase: Loading markup database: 85.00% in 00:21:13, ETA 00:03:44
     [java] 15/08/07 20:45:54 INFO db.MarkupDatabase: Loading markup database: 86.00% in 00:21:29, ETA 00:03:29
     [java] 15/08/07 20:46:09 INFO db.MarkupDatabase: Loading markup database: 87.00% in 00:21:45, ETA 00:03:15
     [java] 15/08/07 20:46:26 INFO db.MarkupDatabase: Loading markup database: 88.00% in 00:22:01, ETA 00:03:00
     [java] 15/08/07 20:46:41 INFO db.MarkupDatabase: Loading markup database: 89.00% in 00:22:17, ETA 00:02:45
     [java] 15/08/07 20:46:57 INFO db.MarkupDatabase: Loading markup database: 90.00% in 00:22:32, ETA 00:02:30
     [java] 15/08/07 20:47:13 INFO db.MarkupDatabase: Loading markup database: 91.00% in 00:22:48, ETA 00:02:15
     [java] 15/08/07 20:47:28 INFO db.MarkupDatabase: Loading markup database: 92.00% in 00:23:04, ETA 00:02:00
     [java] 15/08/07 20:47:44 INFO db.MarkupDatabase: Loading markup database: 93.00% in 00:23:20, ETA 00:01:45
     [java] 15/08/07 20:47:59 INFO db.MarkupDatabase: Loading markup database: 94.00% in 00:23:35, ETA 00:01:30
     [java] 15/08/07 20:48:15 INFO db.MarkupDatabase: Loading markup database: 95.00% in 00:23:50, ETA 00:01:15
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8192
     [java]     at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:546)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1743)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1614)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1652)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1748)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:558)
     [java]     at org.wikipedia.miner.db.MarkupDatabase.loadFromXmlFile(Unknown Source)
     [java]     at org.wikipedia.miner.db.WEnvironment.buildEnvironment(Unknown Source)
     [java]     at org.wikipedia.miner.util.EnvironmentBuilder.main(Unknown Source)
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 43 minutes 58 seconds

```

Any ideas?

**Comment by vshvedov** [comment]
Btw, does `BUILD SUCCESSFUL` message means something?

**Comment by Neuw84** [comment]
Use my fork, bug related to the XML In the Java Library.

-----Mensaje original-----
De: "Vlad Shvedov" notifications@github.com
Enviado: ‎07/‎08/‎2015 22:12
Para: "dnmilne/wikipediaminer" wikipediaminer@noreply.github.com
Asunto: [wikipediaminer] ant build-database fails (#28)

Tested using 6,7,8 JDK, Ubuntu 15.04 x64 - it keep fails with an output:
     [java] 15/08/07 20:45:37 INFO db.MarkupDatabase: Loading markup database: 85.00% in 00:21:13, ETA 00:03:44
     [java] 15/08/07 20:45:54 INFO db.MarkupDatabase: Loading markup database: 86.00% in 00:21:29, ETA 00:03:29
     [java] 15/08/07 20:46:09 INFO db.MarkupDatabase: Loading markup database: 87.00% in 00:21:45, ETA 00:03:15
     [java] 15/08/07 20:46:26 INFO db.MarkupDatabase: Loading markup database: 88.00% in 00:22:01, ETA 00:03:00
     [java] 15/08/07 20:46:41 INFO db.MarkupDatabase: Loading markup database: 89.00% in 00:22:17, ETA 00:02:45
     [java] 15/08/07 20:46:57 INFO db.MarkupDatabase: Loading markup database: 90.00% in 00:22:32, ETA 00:02:30
     [java] 15/08/07 20:47:13 INFO db.MarkupDatabase: Loading markup database: 91.00% in 00:22:48, ETA 00:02:15
     [java] 15/08/07 20:47:28 INFO db.MarkupDatabase: Loading markup database: 92.00% in 00:23:04, ETA 00:02:00
     [java] 15/08/07 20:47:44 INFO db.MarkupDatabase: Loading markup database: 93.00% in 00:23:20, ETA 00:01:45
     [java] 15/08/07 20:47:59 INFO db.MarkupDatabase: Loading markup database: 94.00% in 00:23:35, ETA 00:01:30
     [java] 15/08/07 20:48:15 INFO db.MarkupDatabase: Loading markup database: 95.00% in 00:23:50, ETA 00:01:15
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8192
     [java]     at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:546)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1743)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1614)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1652)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1748)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
     [java]     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:558)
     [java]     at org.wikipedia.miner.db.MarkupDatabase.loadFromXmlFile(Unknown Source)
     [java]     at org.wikipedia.miner.db.WEnvironment.buildEnvironment(Unknown Source)
     [java]     at org.wikipedia.miner.util.EnvironmentBuilder.main(Unknown Source)
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 43 minutes 58 seconds

Any ideas?

**Comment by vshvedov** [comment]
Cool stuff, @Neuw84, thanks.

**Comment by vshvedov** [comment]
Hi @Neuw84, just tried your fork. The `mvn package` ends with:

```
Downloaded: https://repo.maven.apache.org/maven2/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar (1465 KB at 1875.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-core/1.2.0/hadoop-core-1.2.0.jar (4102 KB at 1511.8 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] wikipedia-miner ................................... SUCCESS [0.001s]
[INFO] wikipedia-miner-core .............................. SUCCESS [1:13.044s]
[INFO] Hadoop Job ........................................ FAILURE [11.832s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:25.012s
[INFO] Finished at: Sat Aug 08 00:36:49 EEST 2015
[INFO] Final Memory: 29M/462M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wikipedia-miner-extract: Could not resolve dependencies for project org.wikipedia-miner:wikipedia-miner-extract:jar:1.2.4: Could not find artifact org.wikipedia-miner:wikipedia-miner-core:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wikipedia-miner-extract
```
Am I'm missing something?

**Comment by vshvedov** [comment]
@Neuw84 could you please also explain a little: I see the architecture of the new wikiminer (here and in your fork) differs from the zipped 1.2 version I was using before. Should database be built of CSVs and dump before everything? Previously it was a `and build-database` step — what should be done now?

**Comment by snoodlupa** [comment]
Hi, I follow all instruction in this tutorial https://github.com/dnmilne/wikipediaminer/wiki/Installing-the-java-api

```
But when I do the ant build-database, I have this error
    build-database:
     [echo] Creating the database
     [java] [Fatal Error] :1:1: Content is not allowed in prolog.
     [java] Exception in thread "main" org.xml.sax.SAXParseException; systemId: file:/Users/Matteo/Desktop/NLP_PROJECT/configs/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
     [java]     at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
     [java]     at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
     [java]     at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
     [java]     at org.wikipedia.miner.util.WikipediaConfiguration.<init>(Unknown Source)
     [java]     at org.wikipedia.miner.util.EnvironmentBuilder.main(Unknown Source)
     [java] Java Result: 1
```

In particular I have the wikipedia-template.xml and the other 3 config file in the right folder.
I discover that also if I have a blank directory, the error is always the same.

I verify in xml validate site http://www.xmlvalidation.com/ the wikipedia-template.xml and it is correct..

**Comment by snoodlupa** [comment]
Is dead this project?
